services:
  - type: web
    name: plagiasense-backend
    runtime: python
    rootDir: backend

    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: RATE_LIMIT_IP
        value: "100 per hour"
      - key: RATE_LIMIT_USER
        value: "200 per day"
      - key: CORS_ORIGINS
        value: "*"
