import React, { useState } from 'react';
import api from '../utils/api';

export default function AIDetect() {
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [pdfLoading, setPdfLoading] = useState(false);

  const handleScan = async () => {
    setLoading(true);
    setResult(null);
    try {
const res = await api.post('/api/scan/detect', { text });
      setResult(res.data);
    } catch (err) {
      const msg = err?.response?.data?.error || err?.message || 'AI content classification failed.';
      window.dispatchEvent(new CustomEvent('plagiasense:toast', { detail: { type: 'error', message: msg } }));
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = async (scanId) => {
    if (!scanId) return;
    setPdfLoading(true);
    try {
      const response = await api.get(`/reports/${scanId}/pdf`, {
        responseType: 'blob'
      });
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const link = document.createElement('a');
      link.href = window.URL.createObjectURL(blob);
      link.download = `report_${scanId}.pdf`;
      link.click();
    } catch (err) {
      alert('Failed to download PDF report.');
    } finally {
      setPdfLoading(false);
    }
  };

  const getHeatmapColor = (score) => {
    // Score is 0 - 100 representing probability of AI.
    // We map this score to red opacities.
    const opacity = (score / 100) * 0.5;
    return {
      backgroundColor: `rgba(239, 68, 68, ${opacity})`,
      borderBottom: score > 50 ? `2px solid rgba(239, 68, 68, ${opacity + 0.2})` : 'none',
      padding: '2px 4px',
      borderRadius: '4px',
      marginRight: '4px',
      display: 'inline-block'
    };
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 animate-[fadeIn_0.4s_ease-out]">
      <div>
        <h1 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-400">
          Advanced AI Classifier
        </h1>
        <p className="text-slate-400 mt-1">Ensemble detection pipeline scanning vocabulary richness, entropy, predictability, and stylometrics.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Input Panel */}
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-card p-6 rounded-2xl border border-slate-700 bg-slate-800/80">
            <textarea 
              value={text} 
              onChange={e => setText(e.target.value)} 
              placeholder="Paste your essay or text to analyze for AI predictability patterns (e.g. ChatGPT, GPT-4, Claude)..." 
              className="w-full h-80 p-4 bg-slate-900 rounded-xl border border-slate-700 focus:border-indigo-500 outline-none resize-none mb-4 text-slate-100 transition focus:ring-2 focus:ring-indigo-500/20"
              disabled={loading}
            ></textarea>
            <div className="flex justify-end">
              <button 
                onClick={handleScan} 
                disabled={loading || !text.trim()} 
                className="w-full sm:w-auto px-8 py-3 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 rounded-xl text-white font-bold transition shadow-lg shadow-blue-500/20 disabled:opacity-50 active:scale-95"
              >
                {loading ? 'Analyzing Syntactic Patterns...' : 'Analyze Writing Style'}
              </button>
            </div>
          </div>

          {result && (
            <div className="glass-card p-6 rounded-2xl border border-slate-700 bg-slate-800/80 space-y-4 animate-[fadeIn_0.5s_ease-out]">
              <h2 className="text-xl font-bold text-slate-200">AI Likelihood Heatmap</h2>
              <p className="text-sm text-slate-400">Sentences are highlighted with red intensity corresponding to how likely they are generated by a LLM.</p>
              
              <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 leading-relaxed text-slate-300 max-h-96 overflow-y-auto">
                {result.ai_heatmap?.map((item, idx) => (
                  <span 
                    key={idx} 
                    style={getHeatmapColor(item.ai_likelihood)}
                    title={`AI probability: ${item.ai_likelihood}%`}
                  >
                    {item.text}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right Info Panel */}
        <div className="space-y-6">
          {/* Quick Metrics */}
          {result && (
            <div className="glass-card p-6 rounded-2xl border border-slate-700 bg-slate-800/80 text-center space-y-4 animate-[fadeIn_0.5s_ease-out]">
              <h2 className="text-lg font-bold text-slate-300">Style Analysis</h2>
              
              <div className="relative inline-flex items-center justify-center p-4">
                <div className={`text-5xl font-black ${result.ai_generated ? 'text-indigo-500' : 'text-green-500'}`}>
                  {result.ai_generated ? 'AI Text' : 'Human Text'}
                </div>
              </div>
              <p className="text-sm text-slate-400 px-4">
                We are {result.ai_confidence}% confident that this text is written by {result.ai_generated ? 'an Artificial Intelligence' : 'a Human author'}.
              </p>
              
              <div className="border-t border-slate-700 pt-4 flex justify-around text-xs text-left">
                <div className="w-1/2 pr-2">
                  <span className="block text-slate-400">Vocabulary Richness</span>
                  <span className="font-bold text-slate-200 text-sm">{Math.round(result.stylometry?.vocabulary_richness * 100)}%</span>
                </div>
                <div className="w-1/2 pl-2">
                  <span className="block text-slate-400">Text Predictability</span>
                  <span className="font-bold text-slate-200 text-sm">{Math.round((100 - result.perplexity?.perplexity_proxy) * 10) / 10}%</span>
                </div>
              </div>

              <div className="border-t border-slate-700 pt-4">
                <button
                  onClick={() => downloadPDF(result.scan_id)}
                  disabled={pdfLoading}
                  className="w-full py-2.5 bg-slate-900 hover:bg-slate-850 border border-slate-700 rounded-xl text-slate-200 font-bold transition text-sm active:scale-95 disabled:opacity-50"
                >
                  {pdfLoading ? 'Generating PDF...' : 'Download PDF Report'}
                </button>
              </div>
            </div>
          )}

          {/* Stylometric parameters list */}
          {result && (
            <div className="glass-card p-6 rounded-2xl border border-slate-700 bg-slate-800/80 space-y-4 animate-[fadeIn_0.5s_ease-out]">
              <h3 className="text-md font-bold text-indigo-400">Stylometric & Perplexity Metrics</h3>
              <div className="space-y-3 text-sm">
                <div className="flex justify-between border-b border-slate-700/50 pb-2">
                  <span className="text-slate-400">Avg Sentence Length</span>
                  <span className="font-semibold text-slate-200">{result.stylometry?.avg_sentence_length} words</span>
                </div>
                <div className="flex justify-between border-b border-slate-700/50 pb-2">
                  <span className="text-slate-400">Sentence Length Variance</span>
                  <span className="font-semibold text-slate-200">{result.stylometry?.sentence_length_variance}</span>
                </div>
                <div className="flex justify-between border-b border-slate-700/50 pb-2">
                  <span className="text-slate-400">Stopword Density</span>
                  <span className="font-semibold text-slate-200">{Math.round(result.stylometry?.stopword_density * 100)}%</span>
                </div>
                <div className="flex justify-between border-b border-slate-700/50 pb-2">
                  <span className="text-slate-400">Sentence structure variation</span>
                  <span className="font-semibold text-slate-200">{result.perplexity?.burstiness} (Burstiness)</span>
                </div>
                <div className="flex justify-between border-b border-slate-700/50 pb-2">
                  <span className="text-slate-400">Duplicate Bigrams</span>
                  <span className="font-semibold text-slate-200">{Math.round(result.perplexity?.duplicate_bigram_ratio * 100)}%</span>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
